- name: create {{ hdfs_namenode_name_dirs }} dirs for namenode
  file: path={{ item }} state=directory owner={{ hadoop_user }} group={{ hadoop_user }} mode=0755
  with_items:
    - "{{ hdfs_namenode_name_dirs }}"

- name: put systemd unit file 
  template: src=hdfs-namenode.service.j2 dest=/etc/systemd/system/hdfs-namenode.service owner=root group=root mode=0644

- name: reload systemd 
  shell: systemctl daemon-reload 

- name: start service hdfs-namenode 
  service: name=hdfs-namenode.service state=restarted enabled=yes
